from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base
from config import settings
import os

# We use the SQLite proxy generated by Sub-Agent 10 if USE_MOCK_SNOWFLAKE is True
database_url = settings.DATABASE_URL
if settings.USE_MOCK_SNOWFLAKE:
    # Ensure URL is formatted correctly for SQLAlchemy
    pass
else:
    # Connect to actual snowflake warehouse using settings
    database_url = f"snowflake://{settings.SNOWFLAKE_USER}:{settings.SNOWFLAKE_PASSWORD}@{settings.SNOWFLAKE_ACCOUNT}/"

engine = create_engine(
    database_url, connect_args={"check_same_thread": False} if "sqlite" in database_url else {}
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
